# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [19]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
import time

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [20]:
# Load the csv exported in Part I to a DataFrame
df = pd.read_csv("output_data/cities.csv")
del df["Unnamed: 0"]
df

,City Name,Country,Date,Latitude,Langitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (MPH)
0,mataura,NZ,2020-04-11 01:58:10,-46.19,168.86,68.00,65,0,1.99
1,sahuaripa,MX,2020-04-11 02:01:37,29.05,-109.23,64.35,22,0,3.69
2,tessalit,ML,2020-04-11 02:01:37,20.20,1.01,78.96,14,40,7.61
3,mecca,SA,2020-04-11 02:00:02,21.43,39.83,69.04,28,81,7.29
4,bredasdorp,ZA,2020-04-11 02:01:37,-34.53,20.04,59.00,93,100,1.12
...,...,...,...,...,...,...,...,...,...
551,houma,US,2020-04-11 02:04:07,29.60,-90.72,64.62,63,1,5.82
552,riosucio,CO,2020-04-11 02:04:07,5.42,-75.70,62.53,57,100,1.25
553,ahuimanu,US,2020-04-11 02:03:23,21.44,-157.84,79.84,58,90,5.82
554,sao miguel do araguaia,BR,2020-04-11 02:00:34,-13.28,-50.16,73.38,85,2,1.63
555,narasannapeta,IN,2020-04-11 02:04:08,18.42,84.05,86.79,58,0,6.35

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [33]:
#Get the locations from the data set
locations = df[['Latitude', 'Langitude']]
#Get the magnitude from the data
weights =df['Humidity (%)']
#Set up your map
fig = gmaps.figure(layout={'width': '700px', 
                           'height': '200px',
                           'border': '1px solid black',
                           'padding': '1px'
                          })
heatmap_layer = gmaps.heatmap_layer(
    locations, weights= weights, max_intensity=df["Humidity (%)"].max(), point_radius=4.0)
# adds heatmap layer to original map
fig.add_layer(heatmap_layer)
fig

Figure(layout=FigureLayout(border='1px solid black', height='200px', padding='1px', width='700px'))

In [23]:

# fig = gmaps.figure?

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [24]:
# Narrow down the cities to fit weather conditions
weather_df= df.loc[(df["Temperature (F)"]>70) & 
                   (df["Temperature (F)"]<80)&
                   (df["Wind Speed (MPH)"]<10)&
                   (df["Cloudiness (%)"]==0),:]
weather_df

,City Name,Country,Date,Latitude,Langitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (MPH)
321,nioro,GM,2020-04-11 02:03:06,13.35,-15.75,71.42,62,0,6.76
493,coahuayana,MX,2020-04-11 02:03:45,18.73,-103.68,75.27,61,0,3.89
530,ormara,PK,2020-04-11 02:03:56,25.21,64.64,79.38,68,0,0.81
532,jagdispur,IN,2020-04-11 02:03:57,25.48,84.42,77.00,83,0,6.93

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [25]:
hotel_df= weather_df
hotel_df["Hotel Name"] = ""
hotel_df["Hotel Latitude"] = ""
hotel_df["Hotel Langitude"] = ""
hotel_df

C:\Users\ahmad\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\ahmad\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\ahmad\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,City Name,Country,Date,Latitude,Langitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (MPH),Hotel Name,Hotel Latitude,Hotel Langitude
321,nioro,GM,2020-04-11 02:03:06,13.35,-15.75,71.42,62,0,6.76,,,
493,coahuayana,MX,2020-04-11 02:03:45,18.73,-103.68,75.27,61,0,3.89,,,
530,ormara,PK,2020-04-11 02:03:56,25.21,64.64,79.38,68,0,0.81,,,
532,jagdispur,IN,2020-04-11 02:03:57,25.48,84.42,77.00,83,0,6.93,,,

In [26]:
# sets constant parameters for url
params = {
    "keyword": "hotel",
    "radius": 5000,
    "type": "hotel",
    "key": g_key
}

# iterates through every index and and row
for index, row in hotel_df.iterrows():
# adds timer on loop
    time.sleep(1)
# sets the location with lat, lan
    location = "{0},{1}".format(row["Latitude"], row["Langitude"])
# adds coordinates to params
    params["location"] = location
# base url
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# adds params to url
    response = requests.get(base_url, params=params).json()
# if a hotel exists within 5000 m, store its name, lat, and lng into df. If not, skip it
    try:
        hotel_df.loc[index, 'Hotel Name'] = response["results"][0]["name"]
        hotel_df.loc[index, 'Hotel Latitude'] = response["results"][0]["geometry"]["location"]["lat"]
        hotel_df.loc[index, 'Hotel Langitude'] = response["results"][0]["geometry"]["location"]["lng"]
    except (KeyError, IndexError):
        print("No hotels in this radius... skipping.")

No hotels in this radius... skipping.

In [27]:
hotel_df

,City Name,Country,Date,Latitude,Langitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (MPH),Hotel Name,Hotel Latitude,Hotel Langitude
321,nioro,GM,2020-04-11 02:03:06,13.35,-15.75,71.42,62,0,6.76,,,
493,coahuayana,MX,2020-04-11 02:03:45,18.73,-103.68,75.27,61,0,3.89,Hotel Posada NavideÃ±a,18.6844,-103.667
530,ormara,PK,2020-04-11 02:03:56,25.21,64.64,79.38,68,0,0.81,Zero Point Ormara,25.2494,64.5963
532,jagdispur,IN,2020-04-11 02:03:57,25.48,84.42,77.00,83,0,6.93,Hotel Nirmla Inn,25.4795,84.4319

In [28]:
# delete that rows that doesn't have any hotel in that city(cleaning data)
hotel_data_df = hotel_df.loc[hotel_df["Hotel Name"] != ""]
hotel_data_df

,City Name,Country,Date,Latitude,Langitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (MPH),Hotel Name,Hotel Latitude,Hotel Langitude
493,coahuayana,MX,2020-04-11 02:03:45,18.73,-103.68,75.27,61,0,3.89,Hotel Posada NavideÃ±a,18.6844,-103.667
530,ormara,PK,2020-04-11 02:03:56,25.21,64.64,79.38,68,0,0.81,Zero Point Ormara,25.2494,64.5963
532,jagdispur,IN,2020-04-11 02:03:57,25.48,84.42,77.00,83,0,6.93,Hotel Nirmla Inn,25.4795,84.4319

In [29]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City Name}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_data_df.iterrows()]
locations = hotel_data_df[["Hotel Latitude", "Hotel Langitude"]]

In [30]:
# Add marker layer ontop of heat map
# set layout properties
figure_layout = {
    'width': '400px',
    'height': '265px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations, info_box_content= hotel_info)
# Add the layer to the map
fig.add_layer(markers)
# Display Map
fig

Figure(layout=FigureLayout(border='1px solid black', height='265px', margin='0 auto 0 auto', padding='1px', wiâ€¦